### ISSUE TITLE
Option to Flip the Display

### ISSUE THREAD

**Issue by ashields1965** [protostax/ProtoStax_ISS_Tracker#3]
The default orientation for the display, when attached to a Raspberry Pi puts the power socket of the Pi at the top-right. To make wall mounting the whole thing a bit tidier, would it be possible to have an option to flip the display by 180 degrees. This would mean the power socket would be at the bottom left.

**Comment by jplegat** [comment]
I think there might be a solution here https://pillow.readthedocs.io/en/5.1.x/handbook/tutorial.html?highlight=Rotate

**Comment by sridharrajagopal** [comment]
Thanks @jplegat! Yes, the easiest solution is to just flip the display programmatically. You can mount it on the wall in the orientation you desire, and then just adjust the orientation output to the screen. 

-Sridhar

**Comment by sridharrajagopal** [comment]
At the end of drawISS, *before* you return imageBlack, imageRed, you can 

imageRed = imageRed.transpose(Image.ROTATE_180)
imageBlack = imageBlack.transpose(Image.ROTATE_180)

**Comment by ashields1965** [comment]
Thanks :)
