### ISSUE TITLE
Small mistake in the DISPLAY_REFRESH_INTERVAL test

### ISSUE THREAD

**Issue by RaspiColas** [protostax/ProtoStax_ISS_Tracker#8]
When changing the DISPLAY_REFRESH_INTERVAL to higher value (good idea as the epaper does not appreciate to be refreshed every 30 seconds!) it does not work as there is a mistake in the test line:

        if ((len(positions) >= 1) and ((len(positions)-1) % DISPLAY_REFRESH_INTERVAL)):

should be

        if ((len(positions) >= 1) and ((len(positions)-1) % DISPLAY_REFRESH_INTERVAL) == 0):

**Comment by sridharrajagopal** [comment]
Good catch! Fixed in the latest commit. 

Thanks for your help!
Sridhar
